### ISSUE TITLE
Remove Sphinx Common Constraint

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/edx-lint#338]
## Description
- PR https://github.com/openedx/edx-lint/pull/306 added `Sphinx` in common constraints 

## TODO
- [ ] Investigate if it is safe to remove the common constraint now
- [ ] Create follow up PR in edx-platform to test that the new version does not conflicts with any other package.

**Comment by robrap** [comment]
Closing. This common constraint was just removed in this PR: https://github.com/openedx/edx-lint/pull/349/files
