### ISSUE TITLE
Unpin importlib-metadata

### ISSUE THREAD

**Issue by timmc-edx** [openedx/edx-lint#407]
In https://github.com/openedx/edx-lint/pull/406 we pinned importlib-metadata to before 7.x. Once https://github.com/open-telemetry/opentelemetry-python/issues/3570 resolves we should unpin this.

This pin is in place because we [want to use opentelemetry from edx-django-utils](https://github.com/openedx/edx-django-utils/issues/389). Normally this could be added as a constraint in edx-django-utils, where we're adding the opentelemetry dependency. However, when we compile pip-tools.txt in dependent IDA repos, that layer ends up using version 7.x, and then there's no undoing that when compiling base.txt. So we need to pin it globally, for now.

**Comment by zameel7** [comment]
@timmc-edx, can we unpin this now? Seems like https://github.com/open-telemetry/opentelemetry-python/issues/3570 is resolved.

**Comment by timmc-edx** [comment]
Ah yes, thank you! I had forgotten to subscribe to that issue.

**Comment by zameel7** [comment]
> Ah yes, thank you! I had forgotten to subscribe to that issue.

Any time! Hope we can close this issue now. @timmc-edx
