### ISSUE TITLE
No `ci` in comit lint config

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/edx-lint#427]
I noticed that commitlint config doesn't support `ci`. 

https://github.com/openedx/edx-lint/blob/596689d8ef37616a073e5147a3d9e2af9f36a2b1/commitlint.config.js#L66C1-L66C104

Is there a reason behind it? @feanil @sarina

**Comment by feanil** [comment]
The full spec is here: https://docs.openedx.org/projects/openedx-proposals/en/latest/best-practices/oep-0051-bp-conventional-commits.html#specification

We support build and test instead which can be a bit more precise and useful.
